#!/usr/bin/env python

import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import os
import subprocess
import argparse
import textwrap
import sys
import numpy as np
import itertools


"""
NAME: snv_estimator.py is a python scripy, optionally being used as a package, is to estimate the pairwise SNV rates for a FASTA file.
"""


def calc_snv_per_pair(args):
    # this function is to calculate the SNV rate between two aligned sequences 
    identifier, seq1_header, seq2_header, seq1, seq2 = args

    snv = 0
    non_gap_len = 0
    gap_len = 0
    for i in range(len(seq1)):
        
        SEQ1 = seq1[i].upper()
        SEQ2 = seq2[i].upper()

        if (SEQ1 != '-') and (SEQ2 != '-'):
            non_gap_len += 1
            if SEQ1 != SEQ2:
                snv += 1
            else:
                snv += 0
        else:
            gap_len += 1
    
    if non_gap_len != 0:
        snv_rate = float(snv/non_gap_len)
    else:
        sys.stdout.write('There are too many gaps between {} and {}, hence we assign NAN.\n'.format(seq1_header, seq2_header))
        snv_rate = np.nan

    gap_ratio = float(gap_len/len(seq1))        


    return [identifier, seq1_header, seq2_header, snv_rate, snv, gap_ratio]

def calc_snv_all_pairs(aln_fasta):
    # aln_fasta: An aligned fasta file.
    fasta_dict = SeqIO.to_dict(SeqIO.parse(aln_fasta, 'fasta'))
    pairs = itertools.combinations(fasta_dict, 2)
    identifier = os.path.basename(aln_fasta)
    identifier = os.path.splitext(identifier)[0] # identifier is generated by drop the suffix of the input fasta file.
    for pair in pairs:
        seq1_header, seq2_header = pair
        seq1 = fasta_dict[seq1_header].seq
        seq2 = fasta_dict[seq2_header].seq
        packed_args = [identifier, seq1_header, seq2_header, seq1, seq2]
        snv_est = calc_snv_per_pair(packed_args)
        yield snv_est
        
def add_metadata(snv_generator, md_df, entry_id):
    # snv_generator: the generator which stores SNV information
    # md_df: the metadata of genomes
    # This function is to append metadata to the pairwise SNV rates
    cols = md_df.columns.to_list()
    cols.remove(entry_id)
    for entry in snv_generator:
        seq1 = entry[1]
        seq2 = entry[2]
        packed_args = [[md_df, col, entry_id, seq1, seq2] for col in cols]
        mds = map(fetch_md, packed_args)         
        yield itertools.chain(entry, mds)
                  
def fetch_md(args):
    md_df, col_name, entry_id, seq1, seq2 = args
    seq1_md = md_df.loc[md_df[entry_id] == seq1, col_name].iloc[0]
    seq2_md = md_df.loc[md_df[entry_id] == seq2, col_name].iloc[0]
    if pd.api.types.is_float_dtype(md_df[col_name]) or pd.api.types.is_integer_dtype(md_df[col_name]):
        seq1_seq2_pair = seq1_md - seq2_md
    else:
        seq1_seq2_pair = str(seq1_md) + "$" + str(seq2_md)
    
    return seq1_seq2_pair
        
                     
if __name__ == "__main__":
    def read_args(args):
    # This function is to parse arguments

        parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                         description = textwrap.dedent('''\
                                         This program is to estimate pairwise SNV rates for a fasta file.
                                         '''),
                                        epilog = textwrap.dedent('''\
                                        examples: 
                                       '''))
        parser.add_argument('--fasta',
                        nargs = '?',
                        help = 'Input the FASTA file which contains aligned multiple sequences.',
                        type = str,
                        default = None)

        parser.add_argument('--metadata',
                        nargs = '?',
                        help = 'Input the metadata you would like to append to the pairwise SNV rates.',
                        type = str,
                        default = None)
                        
        parser.add_argument('--entry_col',
                        nargs = '?',
                        help = 'Specify the column which contains the entries (i.e. FASTA headers). Use this feature only when --metadata option is being used.',
                        type = str,
                        default = None)
        
        parser.add_argument('--cols_kept_o_rm',
                            nargs = '?',
                            help = "Input the metadata columns you want to keep (delimited by [;]) or remove (delimited by [,]) from the whole input metadata table. default [None]. Use this feature only when --metadata option is being used.",
                            type = str,
                            default = None)     

        parser.add_argument('--opt_tab',
                        nargs = '?',
                        help = 'Specify the output table for holding pairwise SNV rates.',
                        type = str,
                        default = None)    
        
        return vars(parser.parse_args())    
    
    snv_generator = calc_snv_all_pairs("group_1003.fa.aln")
    md_df = pd.read_csv("mag_metadata.tsv", sep = "\t", index_col = False)
    # df = pd.DataFrame(snv_generator)
    # df.to_csv("test.tsv", sep = "\t", index = False, header = False)
    # test = add_metadata(snv_generator, md_df, 'mag_id')
    # df_ = pd.DataFrame(test)
    # print(df)
    